sudo: false

language: python

python:
  - 2.7
  - 3.5

cache:
  - pip

env:
  - BIGBUILD_GIT_BRANCH=$TRAVIS_BRANCH

install:
  - pip install -r requirements.txt

script:
  - make test

after_success:
  - coveralls
