sudo: false

language: python

python:
  - 2.7
  - 3.5

cache:
  - pip

install:
  - pip install -r requirements.txt

script:
  - flake8 bigbuild
  - coverage run setup.py test

after_success:
  - coveralls
