sudo: false

language: python

python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"

cache:
  - pip

env:
  global:
  - BIGBUILD_GIT_BRANCH=$TRAVIS_BRANCH
  matrix:
    - DJANGO_VERSION=1.10.*
    - DJANGO_VERSION=1.11.*
    - DJANGO_VERSION=2.0.*

matrix:
  exclude:
  - python: "2.7"
    env: DJANGO_VERSION=2.0.*

install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION

script:
  - make test

after_success:
  - coveralls
